#pragma config(Sensor, S1,     color,          sensorEV3_Color)
#pragma config(Sensor, S2,     button,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          colorMotor,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*colors:
0= none
1= black
2= blue
3= green
4= yellow
5= red
6= white
7= brown*/

task main()
{
	int mode = 1;
	int speed = 20;
	int count = 0;

	while(mode == 1)
	{
		if(SensorValue(button) == 1)
		{
			count = 1;
			resetMotorEncoder(colorMotor);
			while(getMotorEncoder(colorMotor) < 90 && count == 1 && getMotorEncoder(colorMotor) > -90)
			{
				motor[colorMotor] = speed;
			}
			if(getMotorEncoder(colorMotor) >= 90 || getMotorEncoder(colorMotor) <= -90)
			{
				motor[colorMotor] = 0;
				speed = -speed;
				resetMotorEncoder(colorMotor);
				count = 0;
			}
		}
	}
}
